### PR TITLE
rcnnnghm/k8s release docs

### PR DESCRIPTION
**Pull request by rcnnnghm**
List of items changed:

- Removed references to managed.hopsworks.ai
- Changed "Setup and Installation" to "Setup and Administration"
- Moved "Common" to "Managed" and left as tab in UI for review
- Moved items from "Administration" tab into "Setup and Administration"
- Removed references to karamel

**NB** Need to remove "Managed" tab before merge.

### CODE REVIEW

**Comment by SirOibaf** [comment]
Couple of comments: 
- Need to remove the Hopsworks installer section
- Step 6 on the different pages point to some google collab notebooks which I'm not sure it's up to date, as well as the hops-examples repo which has been archived in favour of the hopsworks-tutorial repo

**Comment by SirOibaf** [comment]
- the URL for the helm repository only has the development helm charts, not the released one. My understanding was that users are supposed to first agree to the eval/startup license (here: https://www.hopsworks.ai/try) which will then reveal the helm repo URL. Right now it's the documentation -  I think the documentation should link to the link above.
- The alias for the helm repo when cloned should be `hopsworks` not `hopsworks-dev`.
- You don't need to create the secret anymore, nor provide username and password to register the helm chart repo - So we should remove those from the documetation 
- We should remove the ` --devel ` flag from the `helm install` documentation since that's only needed from not -released verisons.

**Comment by SirOibaf** [comment]
- The documentation for AWS contains a values file which I wrote and excludes some stuff I don't needed (e.g. the Kserve) - Also some of the attributes have changes and the values.yaml file is no longer valid. We should remove it from the documentation.

**Comment by rcnnnghm** [comment]
> Couple of comments:
> 
> * Need to remove the Hopsworks installer section
> * Step 6 on the different pages point to some google collab notebooks which I'm not sure it's up to date, as well as the hops-examples repo which has been archived in favour of the hopsworks-tutorial repo

I re-worked the content of the installer section to be a shortened on-premise backgrounder with call
to action of contacting Hopsworks.

**Comment by rcnnnghm** [comment]
> * the URL for the helm repository only has the development helm charts, not the released one. My understanding was that users are supposed to first agree to the eval/startup license (here: https://www.hopsworks.ai/try) which will then reveal the helm repo URL. Right now it's the documentation -  I think the documentation should link to the link above.
> * The alias for the helm repo when cloned should be `hopsworks` not `hopsworks-dev`.
> * You don't need to create the secret anymore, nor provide username and password to register the helm chart repo - So we should remove those from the documetation
> * We should remove the `--devel` flag from the `helm install` documentation since that's only needed from not -released verisons.

These should all be addressed now.

**Comment by rcnnnghm** [comment]
> * The documentation for AWS contains a values file which I wrote and excludes some stuff I don't needed (e.g. the Kserve) - Also some of the attributes have changes and the values.yaml file is no longer valid. We should remove it from the documentation.

I removed the reference to kube kserve in the values.yaml file but I wasn't sure if there were other updates I should do to the values.yaml file. If you have one in mind, I'd be happy to include it.

**Pull request closed without merging**
